menu:
  首页: /
  归档: /archives/
  关于: /about/
  订阅: /atom.xml

widgets:
- search
- menu
# - weibo
- category
- tagcloud

excerpt_link: Read More

fancybox: true

# 友言评论
UYUserId:

# cnzz统计
cnzzId: 1253033676

# JiaThis分享
jiathisUUID:

weibo:
	name:
	uid:
	link:

rss: http://pinkyjie.com/atom.xml
